-- ── enviosrh — Características Avanzadas y Logística ──
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'available';
ALTER TABLE users ADD COLUMN IF NOT EXISTS battery_level INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS signal_quality VARCHAR(20);

ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS proof_img TEXT;
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS proof_signature TEXT;
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS cash_collected NUMERIC(10,2) DEFAULT 0.00;
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS cash_settled BOOLEAN DEFAULT FALSE;
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS cash_settled_at TIMESTAMP WITH TIME ZONE;
