import type { TourStep } from './types';
import { APP_NAME, AI_NAME } from '../../lib/brand';

export const OPERATOR_STEPS: TourStep[] = [
  {
    id: 'hero',
    title: `Bienvenido a ${APP_NAME}`,
    subtitle: 'Tu Super App logística',
    body: 'Gestiona varias personas en tu empresa: operadores, colaboradores y mensajeros. Te guiamos paso a paso.',
    scene: 'hero',
    placement: 'center',
    accent: '#5b8af9',
  },
  {
    id: 'company',
    title: 'Configura tu empresa',
    subtitle: 'Marca y perfil',
    body: 'En Panel Admin → Marca y Perfil define el nombre, logo, colores y datos de contacto de tu negocio.',
    scene: 'hero',
    target: '[data-tour="nav-admin"]',
    placement: 'right',
    accent: '#a78bfa',
  },
  {
    id: 'location',
    title: 'Ubicación de despacho',
    subtitle: 'Un solo clic con GPS',
    body: 'En Marca y Perfil pulsa «Usar mi ubicación» para fijar el punto de salida de tus envíos. También puedes hacerlo al crear cada pedido.',
    scene: 'gps',
    placement: 'center',
    accent: '#22c55e',
  },
  {
    id: 'team',
    title: 'Arma tu equipo',
    subtitle: 'Colaboradores y mensajeros',
    body: 'Panel Admin → Mensajeros: repartidores con GPS. Vendedores: colaboradores que registran pedidos. Usa «Agregar colaborador» en cada pestaña.',
    scene: 'hero',
    target: '[data-tour="nav-admin"]',
    placement: 'right',
    accent: '#f59e0b',
  },
  {
    id: 'new-delivery',
    title: 'Crear envío',
    subtitle: 'Rápido y con mapa',
    body: 'Registra cliente, dirección y productos. Coloca el pin en el mapa, pega un link de Google Maps o usa «Mi ubicación».',
    scene: 'hero',
    target: '[data-tour="nav-nuevo"]',
    placement: 'right',
    accent: '#22c55e',
  },
  {
    id: 'live-map',
    title: 'Mapa en vivo',
    subtitle: 'Visibilidad total',
    body: 'Sigue cada mensajero y envío activo. Las rutas se dibujan automáticamente en el mapa.',
    scene: 'live-map',
    target: '[data-tour="nav-mapa"]',
    placement: 'right',
    accent: '#f59e0b',
  },
  {
    id: 'ai',
    title: AI_NAME,
    subtitle: 'Tu copiloto operativo',
    body: 'Pregunta por envíos pendientes, alertas o resúmenes del día. El botón ✦ abajo a la derecha abre el asistente.',
    scene: 'hero',
    placement: 'center',
    accent: '#5b8af9',
  },
  {
    id: 'route',
    title: 'Ruta inteligente',
    subtitle: 'En tiempo real',
    body: 'Cliente y mensajero comparten la misma ruta con tiempo estimado de llegada.',
    scene: 'map-route',
    placement: 'center',
    accent: '#5b8af9',
  },
  {
    id: 'done',
    title: '¡Listo para operar!',
    subtitle: 'Tu equipo puede entrar ya',
    body: 'Invita colaboradores con su correo. Cada uno verá su propio tour según su rol.',
    scene: 'complete',
    placement: 'center',
    accent: '#22c55e',
  },
];

export const MESSENGER_STEPS: TourStep[] = [
  {
    id: 'hero',
    title: `Hola, mensajero de ${APP_NAME}`,
    subtitle: 'Tu día empieza aquí',
    body: 'Envíos asignados, ruta optimizada y navegación en un solo lugar.',
    scene: 'hero',
    placement: 'center',
    accent: '#f59e0b',
  },
  {
    id: 'gps',
    title: 'Activa tu GPS',
    subtitle: 'Imprescindible',
    body: 'Sin GPS el cliente no puede verte en el mapa. Mantén la app abierta durante la entrega.',
    scene: 'gps',
    placement: 'center',
    accent: '#22c55e',
  },
  {
    id: 'route',
    title: 'Ruta al cliente',
    subtitle: 'Sigue la línea azul',
    body: 'El mapa traza tu camino. Usa Google Maps o Waze si prefieres navegación externa.',
    scene: 'map-route',
    placement: 'center',
    accent: '#5b8af9',
  },
  {
    id: 'proof',
    title: 'Confirmar entrega',
    subtitle: 'QR · Foto · Firma',
    body: 'Escanea el código, toma evidencia y captura la firma del cliente para cerrar el envío.',
    scene: 'delivery-proof',
    placement: 'center',
    accent: '#a78bfa',
  },
  {
    id: 'done',
    title: '¡A rodar!',
    body: 'Toca un envío para ver mapa, chat y acciones de entrega.',
    scene: 'complete',
    placement: 'center',
    accent: '#22c55e',
  },
];

export const CUSTOMER_STEPS: TourStep[] = [
  {
    id: 'hero',
    title: 'Tu pedido en camino',
    subtitle: 'Seguimiento en vivo',
    body: `Aquí verás al repartidor moverse en el mapa hasta tu puerta con ${APP_NAME}.`,
    scene: 'hero',
    placement: 'center',
    accent: '#5b8af9',
  },
  {
    id: 'track',
    title: 'Mapa en tiempo real',
    subtitle: 'Ruta + ETA',
    body: 'La línea azul muestra el recorrido. El contador baja mientras se acerca.',
    scene: 'map-route',
    placement: 'center',
    accent: '#f59e0b',
  },
  {
    id: 'chat',
    title: 'Chat con tu mensajero',
    subtitle: 'Coordina al instante',
    body: 'Escribe si necesitas indicaciones. Verás cuando está escribiendo.',
    scene: 'chat',
    placement: 'center',
    accent: '#5b8af9',
  },
  {
    id: 'rate',
    title: 'Califica tu experiencia',
    subtitle: 'Toca las estrellas',
    body: 'Al recibir, confirma y deja tu opinión. ¡Pruébalo aquí!',
    scene: 'rating',
    placement: 'center',
    accent: '#fbbf24',
  },
  {
    id: 'done',
    title: '¡Disfruta tu pedido!',
    body: 'Recibirás una notificación cuando el mensajero esté cerca.',
    scene: 'complete',
    placement: 'center',
    accent: '#22c55e',
  },
];

export function stepsForRole(role: 'operator' | 'messenger' | 'customer') {
  if (role === 'operator') return OPERATOR_STEPS;
  if (role === 'messenger') return MESSENGER_STEPS;
  return CUSTOMER_STEPS;
}
